route:
  enabled: true
global:
  dynamic:
    plugins:
    - package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
      disabled: true
    - package: ./dynamic-plugins/dist/backstage-community-plugin-ocm-backend-dynamic
      disabled: true
    - package: ./dynamic-plugins/dist/backstage-community-plugin-ocm
      disabled: true
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-adoption-insights
      disabled: true
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-adoption-insights-backend-dynamic
      disabled: true
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights-dynamic
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
    - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic
      disabled: false
upstream:
  backstage:
    extraEnvVarsSecrets:
    - rhdh-secrets
    podSecurityContext:
      fsGroup: 2000
    startupProbe:
      failureThreshold: 3
  postgresql:
    primary:
      podSecurityContext:
        enabled: false
        fsGroup: 3000
  volumePermissions:
    enabled: true
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: gce
      kubernetes.io/ingress.global-static-ip-name: rhdh-static-ip
      ingress.gcp.kubernetes.io/pre-shared-cert: ''
      networking.gke.io/v1beta1.FrontendConfig: rhdh-gke-ingress-security-config
    className: gce
orchestrator:
  enabled: false
  serverlessLogicOperator:
    enabled: true
  serverlessOperator:
    enabled: true
  sonataflowPlatform:
    monitoring:
      enabled: true
    eventing:
      broker:
        name: ''
        namespace: ''
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    externalDBsecretRef: ''
    externalDBName: ''
    externalDBHost: ''
    externalDBPort: ''
    initContainerImage: {{ .Values.upstream.postgresql.image.registry }}/{{
      .Values.upstream.postgresql.image.repository }}:{{ .Values.upstream.postgresql.image.tag
      }}
    createDBJobImage: {{ .Values.upstream.postgresql.image.registry }}/{{
      .Values.upstream.postgresql.image.repository }}:{{ .Values.upstream.postgresql.image.tag
      }}
    jobServiceImage: ''
    dataIndexImage: ''
  plugins:
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{
      "{{inherit}}" }}
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{
      "{{inherit}}" }}
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:{{
      "{{inherit}}" }}
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{
      "{{inherit}}" }}
    disabled: false
