route:
  enabled: true
global:
  dynamic:
    plugins:
    - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic
      disabled: false
    - package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
    - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{
        "{{" }}inherit{{ "}}" }}
      disabled: true
upstream:
  backstage:
    extraEnvVarsSecrets:
    - rhdh-secrets
    podSecurityContext:
      fsGroup: 3000
    startupProbe:
      failureThreshold: 3
    tolerations:
    - key: kubernetes.azure.com/scalesetpriority
      operator: Equal
      value: spot
      effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.azure.com/scalesetpriority
              operator: In
              values:
              - spot
  postgresql:
    primary:
      podSecurityContext:
        enabled: false
        fsGroup: 3000
      tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
        effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.azure.com/scalesetpriority
                operator: In
                values:
                - spot
  volumePermissions:
    enabled: true
  ingress:
    enabled: true
    className: webapprouting.kubernetes.azure.com
    host: {{ .Values.global.host }}
orchestrator:
  enabled: false
  serverlessLogicOperator:
    enabled: true
  serverlessOperator:
    enabled: true
  sonataflowPlatform:
    monitoring:
      enabled: true
    eventing:
      broker:
        name: ''
        namespace: ''
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    externalDBsecretRef: ''
    externalDBName: ''
    externalDBHost: ''
    externalDBPort: ''
    initContainerImage: {{ .Values.upstream.postgresql.image.registry }}/{{
      .Values.upstream.postgresql.image.repository }}:{{ .Values.upstream.postgresql.image.tag
      }}
    createDBJobImage: {{ .Values.upstream.postgresql.image.registry }}/{{
      .Values.upstream.postgresql.image.repository }}:{{ .Values.upstream.postgresql.image.tag
      }}
    jobServiceImage: ''
    dataIndexImage: ''
  plugins:
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{
      "{{inherit}}" }}
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{
      "{{inherit}}" }}
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:{{
      "{{inherit}}" }}
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{
      "{{inherit}}" }}
    disabled: false
