global:
  dynamic:
    plugins: []
  includes:
    - "dynamic-plugins.yaml"
  # use the latest catalog index
  catalogIndex:
    image:
      registry: quay.io
      repository: rhdh/plugin-catalog-index
      tag: "1.10"
# -- Upstream Backstage [chart configuration](https://github.com/backstage/charts/blob/main/charts/backstage/values.yaml)
upstream:
  nameOverride: developer-hub
  commonLabels:
    backstage.io/kubernetes-id: developer-hub
  backstage:
    appConfig:
      backend:
        auth:
          dangerouslyDisableDefaultAuthPolicy: true
          externalAccess:
            - type: static
              options:
                token: test-token
                subject: test-subject
    image:
      pullPolicy: Always
      registry: quay.io
      repository: rhdh-community/rhdh
      tag: next
    extraEnvVars:
      - name: BACKEND_SECRET
        valueFrom:
          secretKeyRef:
            key: backend-secret
            name: '{{ include "rhdh.backend-secret-name" $ }}'
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgres-password
            name: "{{ .Release.Name }}-postgresql"
      # disable telemetry in CI
      - name: SEGMENT_TEST_MODE
        value: "true"
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - name: NODE_ENV
        value: "production"
      - name: ENABLE_CORE_ROOTHTTPROUTER_OVERRIDE
        value: "true"
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml
      - configMapRef: dynamic-plugins-config
        filename: dynamic-plugins-config.yaml
      - configMapRef: dynamic-global-floating-action-button-config
        filename: dynamic-global-floating-action-button-config.yaml
      - configMapRef: dynamic-global-header-config
        filename: dynamic-global-header-config.yaml
      - configMapRef: dynamic-plugins-showcase
        filename: dynamic-plugins.yaml
    startupProbe:
      # This gives enough time upon container startup before the liveness and readiness probes are triggered.
      # Giving (120s = initialDelaySeconds + failureThreshold * periodSeconds) to account for the worst case scenario.
      httpGet:
        path: /.backstage/health/v1/liveness
        port: backend
        scheme: HTTP
      initialDelaySeconds: 30
      timeoutSeconds: 4
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /.backstage/health/v1/readiness
        port: backend
        scheme: HTTP
      # Both liveness and readiness probes won't be triggered until the startup probe is successful.
      # The startup probe is already configured to give enough time for the application to be started.
      # So removing the additional delay here allows the readiness probe to be checked right away after the startup probe,
      # which helps make the application available faster to the end-user.
      # initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 2
      timeoutSeconds: 4
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /.backstage/health/v1/liveness
        port: backend
        scheme: HTTP
      # Both liveness and readiness probes won't be triggered until the startup probe is successful.
      # The startup probe is already configured to give enough time for the application to be started.
      # So removing the additional delay here allows the liveness probe to be checked right away after the startup probe,
      # which helps make the application available faster to the end-user.
      # initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 4
    extraEnvVarsSecrets:
      - rhdh-secrets
      - redis-secret
  ingress:
    host: "{{ .Values.global.host }}"

  service:
    extraPorts:
      - name: http-metrics
        port: 9464
        targetPort: 9464

orchestrator:
  plugins: [] # disable chart-based orchestrator plugins and define above for clarity (may need a new test config to cover helm chart plugins)
  enabled: true
  serverlessLogicOperator:
    enabled: true
  serverlessOperator:
    enabled: true
  sonataflowPlatform:
    monitoring:
      enabled: true
    eventing:
      broker:
        name: ""
        namespace: ""
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
