developerHub:
  flavor: rhdh
app:
  baseUrl: ${BASE_URL:-http://localhost:3000}
  title: Red Hat Developer Hub
organization:
  name: ${ORGANIZATION_NAME}
backend:
  baseUrl: ${BASE_URL:-http://localhost:7007}
  csp:
    connect-src:
      - "'self'"
      - "http:"
      - "https:"
  cors:
    origin: ${BASE_URL:-http://localhost:3000}
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
    credentials: true
  auth:
    keys:
      - secret: temp
    externalAccess:
      - type: static
        options:
          token: ${STATIC_TOKEN:-localmocktoken}
          subject: e2e-tests-ci
  database:
    client: better-sqlite3
    connection: ":memory:"
includeTransitiveGroupOwnership: true
auth:
  environment: production
  session:
    secret: superSecretSecret
  providers:
    oidc:
      production:
        metadataUrl: ${RHBK_BASE_URL}/realms/${RHBK_REALM}
        clientId: ${RHBK_CLIENT_ID}
        clientSecret: ${RHBK_CLIENT_SECRET}
        prompt: auto
        callbackUrl: ${BASE_URL:-http://localhost:7007}/api/auth/oidc/handler/frame
        signIn:
          resolvers:
            - resolver: preferredUsernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: false
        sessionDuration: 3days
catalog:
  import:
    entityFilename: catalog-info.yaml
  rules:
    - allow:
        - API
        - Component
        - Group
        - Location
        - Resource
        - System
        - Template
  providers:
    keycloakOrg:
      default:
        baseUrl: ${RHBK_BASE_URL}
        loginRealm: ${RHBK_REALM}
        realm: ${RHBK_REALM}
        clientId: ${RHBK_CLIENT_ID}
        clientSecret: ${RHBK_CLIENT_SECRET}
        schedule:
          frequency:
            minutes: 1
          timeout:
            minutes: 1
permission:
  enabled: false
dynamicPlugins:
  rootDirectory: /Users/abarbaro/code/rhdh-refactor-auth-providers/dynamic-plugins-root
signInPage: oidc
