kind: Secret
apiVersion: v1
metadata:
  name: postgres-cred
stringData:
  POSTGRES_PASSWORD: tmp
  POSTGRES_PORT: "5432"
  POSTGRES_USER: janus-idp
  POSTGRES_HOST: tmp
  PGSSLMODE: require
  NODE_EXTRA_CA_CERTS: /opt/app-root/src/postgres-crt.pem
  RHDH_RUNTIME_URL: ${RHDH_RUNTIME_URL}
