kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets
data:
  # the followings are place holders that will be replaced by ENV variables by `envsubst` command`
  GITHUB_APP_APP_ID: $GITHUB_APP_APP_ID
  GITHUB_APP_CLIENT_ID: $GITHUB_APP_CLIENT_ID
  GITHUB_APP_PRIVATE_KEY: $GITHUB_APP_PRIVATE_KEY
  GITHUB_APP_CLIENT_SECRET: $GITHUB_APP_CLIENT_SECRET
  GITHUB_APP_JANUS_TEST_APP_ID: $GITHUB_APP_JANUS_TEST_APP_ID
  GITHUB_APP_JANUS_TEST_CLIENT_ID: $GITHUB_APP_JANUS_TEST_CLIENT_ID
  GITHUB_APP_JANUS_TEST_PRIVATE_KEY: $GITHUB_APP_JANUS_TEST_PRIVATE_KEY
  GITHUB_APP_JANUS_TEST_CLIENT_SECRET: $GITHUB_APP_JANUS_TEST_CLIENT_SECRET
  GITHUB_APP_WEBHOOK_URL: $GITHUB_APP_WEBHOOK_URL
  GITHUB_APP_WEBHOOK_SECRET: $GITHUB_APP_WEBHOOK_SECRET
  GITHUB_URL: $GITHUB_URL
  GITHUB_ORG: $GITHUB_ORG
  GITHUB_ORG_2: $GITHUB_ORG_2
  GITLAB_TOKEN: $GITLAB_TOKEN
  K8S_CLUSTER_NAME: $ENCODED_CLUSTER_NAME
  K8S_CLUSTER_API_SERVER_URL: $K8S_CLUSTER_API_SERVER_URL
  K8S_CLUSTER_TOKEN_ENCODED: $K8S_CLUSTER_TOKEN_ENCODED
  OCM_CLUSTER_URL: $OCM_CLUSTER_URL
  OCM_CLUSTER_TOKEN: $OCM_CLUSTER_TOKEN
  KEYCLOAK_BASE_URL: $KEYCLOAK_BASE_URL_ENCODED
  KEYCLOAK_LOGIN_REALM: $KEYCLOAK_LOGIN_REALM_ENCODED
  KEYCLOAK_REALM: $KEYCLOAK_REALM_ENCODED
  KEYCLOAK_CLIENT_ID: $KEYCLOAK_CLIENT_ID_ENCODED
  KEYCLOAK_CLIENT_SECRET: $KEYCLOAK_CLIENT_SECRET_ENCODED
  ACR_SECRET: $ACR_SECRET
  DH_TARGET_URL: $DH_TARGET_URL
  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
  RHDH_BASE_URL: $RHDH_BASE_URL
  RHDH_BASE_URL_HTTP: $RHDH_BASE_URL_HTTP
  KEYCLOAK_AUTH_BASE_URL: $KEYCLOAK_AUTH_BASE_URL
  KEYCLOAK_AUTH_CLIENTID: $KEYCLOAK_AUTH_CLIENTID
  KEYCLOAK_AUTH_CLIENT_SECRET: $KEYCLOAK_AUTH_CLIENT_SECRET
  KEYCLOAK_AUTH_LOGIN_REALM: $KEYCLOAK_AUTH_LOGIN_REALM
  KEYCLOAK_AUTH_REALM: $KEYCLOAK_AUTH_REALM
  REDIS_PASSWORD: $REDIS_PASSWORD_ENCODED
  REDIS_USERNAME: $REDIS_USERNAME_ENCODED
  GITHUB_OAUTH_APP_ID: $GITHUB_OAUTH_APP_ID_ENCODED
  GITHUB_OAUTH_APP_SECRET: $GITHUB_OAUTH_APP_SECRET_ENCODED
type: Opaque
