- name: Ensure workflow namespace is created
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: oc new-project {{ workflow_namespace }}
  register: project_result
  failed_when: project_result.rc not in [0, 1]

# See https://github.com/rhdhorchestrator/orchestrator-helm-chart/blob/gh-pages/README.md#argocd-and-workflow-namespace
- name: Label workflow namespace so that it can be managed by argocd
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: oc label namespace {{ workflow_namespace }} 'argocd.argoproj.io/managed-by={{ gitops_namespace }}'

- name: Capture the dynamic plugins
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: oc get cm dynamic-plugins-rhdh -n {{ rhdh_ns }} -o json | jq '.data."dynamic-plugins.yaml"' -r | awk -F 'package:' '/package:/ {print $2}' | /usr/bin/sed 's/"//g' | grep -e plugin-orchestrator -e plugin-signals -e plugin-notifications
  register: report_dyn_plugins

- name: Debug out relevant dynamic plugins
  debug:
    msg:
      - "DYNAMIC_PLUGINS={{ report_dyn_plugins.stdout_lines | join(',') }}"
      - "{{ report_dyn_plugins.stdout_lines }}"
