- name: Install Helm
  ansible.builtin.import_tasks: tasks/install-helm.yaml

- name: Re-create work directory
  ansible.builtin.file:
    path: "{{ orch_deploy_work_dir }}"
    state: "{{ item }}"
  loop:
    - absent
    - directory

- name: Check if jq is installed
  command: which jq
  register: jq_check
  failed_when: false
  changed_when: false

- name: Install jq on macOS
  when:
    - jq_check.rc != 0
    - ansible_os_family == "Darwin"
  block:
    - name: Try to install jq with Homebrew (if available)
      command: brew install jq
      register: brew_install
      failed_when: false
      changed_when: brew_install.rc == 0

    - name: Download jq binary directly if brew failed
      when: brew_install.rc != 0
      get_url:
        url: https://github.com/stedolan/jq/releases/latest/download/jq-osx-amd64
        dest: "{{ ansible_env.HOME }}/.local/bin/jq"
        mode: '0755'
      delegate_to: localhost

- name: Install required packages on Linux
  package:
    name:
      - jq
    state: present
  become: true
  when:
    - jq_check.rc != 0
    - ansible_os_family != "Darwin"

- name: check yq binary exists
  shell: |
    command -v yq
  register: yq_bin_found
  failed_when: false

- name: install yq binary block
  block:
    - name: Determine yq binary URL based on system
      set_fact:
        yq_url: "{{ 'https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_darwin_amd64' if ansible_os_family == 'Darwin' else 'https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64' }}"
        yq_dest: "{{ ansible_env.HOME }}/.local/bin/yq"

    - name: Ensure .local/bin directory exists
      file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: '0755'

    - name: download yq binary
      get_url:
        url: "{{ yq_url }}"
        dest: "{{ yq_dest }}"
        mode: 0755
      register: yq_download
      retries: 3
      delay: 60
      until: yq_download is success

    - name: Add .local/bin to PATH for current session
      set_fact:
        ansible_env: "{{ ansible_env | combine({'PATH': ansible_env.HOME + '/.local/bin:' + ansible_env.PATH}) }}"

    - name: Verify yq installation
      command: "{{ yq_dest }} --version"
      register: yq_version
      changed_when: false

    - name: Display yq version
      debug:
        msg: "yq installed: {{ yq_version.stdout }}"
  when: yq_bin_found.rc != 0
