- name: Extract image name from image map
  block:
    - name: Get ocp version
      ansible.builtin.shell: oc get clusterversion version -o jsonpath='{.status.desired.version}'
      register: clusterversion_output
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Extract major and minor version
      set_fact:
        openshift_version: "{{ clusterversion_output.stdout.split('.')[0] + '.' + clusterversion_output.stdout.split('.')[1]}}"

    - name: Get brew image
      set_fact:
        image_url: "{{ sf_rc_images[openshift_version]}}"

- name: Create catalogsource for Openshift Serverless Logic
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: logic-136-cr1
      namespace: openshift-marketplace
    spec:
      sourceType: grpc
      image: {{ image_url }}
      displayName: SonataFlow Operator RC
      publisher: Apache
    EOF
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
