## Arbitrary app-config for backwards compatible UI configuration - now with dynamic plugins
dynamicPlugins:
  frontend:
    backstage.plugin-kubernetes:
      mountPoints:
        - mountPoint: entity.page.kubernetes/cards
          importName: EntityKubernetesContent
          config:
            layout:
              gridColumn: "1 / -1"
            if:
              anyOf:
                - hasAnnotation: backstage.io/kubernetes-id
                - hasAnnotation: backstage.io/kubernetes-namespace
    backstage.plugin-notifications:
      dynamicRoutes:
        - importName: NotificationsPage
          menuItem:
            config:
              props:
                titleCounterEnabled: true
                webNotificationsEnabled: false
            importName: NotificationsSidebarItem
          path: /notifications
    backstage.plugin-signals: {}
    backstage-community.plugin-acr:
      mountPoints:
        - mountPoint: entity.page.image-registry/cards
          importName: AcrPage
          config:
            layout:
              gridColumn: 1 / -1
            if:
              anyOf:
                - isAcrAvailable
    backstage-community.plugin-ocm:
      appIcons:
        - name: ocmIcon
          importName: OcmIcon
      dynamicRoutes:
        - path: /ocm
          importName: OcmPage
          menuItem:
            icon: ocmIcon
            text: Clusters
      mountPoints:
        - mountPoint: entity.page.overview/context
          importName: ClusterContextProvider
        - mountPoint: entity.page.overview/cards
          importName: ClusterAvailableResourceCard
          config:
            layout:
              gridColumnEnd:
                lg: "span 4"
                md: "span 6"
                xs: "span 12"
            if:
              allOf:
                - isKind: resource
                - isType: kubernetes-cluster
        - mountPoint: entity.page.overview/cards
          importName: ClusterInfoCard
          config:
            layout:
              gridColumnEnd:
                lg: "span 4"
                md: "span 6"
                xs: "span 12"
            if:
              allOf:
                - isKind: resource
                - isType: kubernetes-cluster
    red-hat-developer-hub.backstage-plugin-bulk-import:
      appIcons:
        - name: bulkImportIcon
          importName: BulkImportIcon
      dynamicRoutes:
        - path: /bulk-import/repositories
          importName: BulkImportPage
          menuItem:
            icon: bulkImportIcon
            text: Bulk import
    red-hat-developer-hub.backstage-plugin-global-header:
      mountPoints:
        - mountPoint: application/header
          importName: GlobalHeader
          config:
            position: above-main-content # above-main-content | above-sidebar
    red-hat-developer-hub.backstage-plugin-global-floating-action-button:
      mountPoints:
        - mountPoint: application/listener
          importName: DynamicGlobalFloatingActionButton
    red-hat-developer-hub.backstage-plugin-quickstart:
      mountPoints:
        - mountPoint: application/provider
          importName: QuickstartDrawerProvider
    red-hat-developer-hub.backstage-plugin-dynamic-home-page:
      dynamicRoutes:
        - path: /
          importName: DynamicHomePage
      mountPoints:
        - mountPoint: application/listener
          importName: VisitListener
        - mountPoint: home.page/cards
          importName: SearchBar
          config:
            layouts:
              xl: {w: 10, h: 1, x: 1}
              lg: {w: 10, h: 1, x: 1}
              md: {w: 10, h: 1, x: 1}
              sm: {w: 10, h: 1, x: 1}
              xs: {w: 12, h: 1}
              xxs: {w: 12, h: 1}
        - mountPoint: home.page/cards
          importName: QuickAccessCard
          config:
            layouts:
              xl: {w: 7, h: 8}
              lg: {w: 7, h: 8}
              md: {w: 7, h: 8}
              sm: {w: 12, h: 8}
              xs: {w: 12, h: 8}
              xxs: {w: 12, h: 8}
        - mountPoint: home.page/cards
          importName: CatalogStarredEntitiesCard
          config:
            layouts:
              xl: {w: 5, h: 4, x: 7}
              lg: {w: 5, h: 4, x: 7}
              md: {w: 5, h: 4, x: 7}
              sm: {w: 12, h: 4}
              xs: {w: 12, h: 4}
              xxs: {w: 12, h: 4}
    backstage-community.plugin-topology:
      mountPoints:
        - mountPoint: entity.page.topology/cards
          importName: TopologyPage
          config:
            layout:
              gridColumn: "1 / -1"
              height: 75vh
            if:
              anyOf:
                - hasAnnotation: backstage.io/kubernetes-id
                - hasAnnotation: backstage.io/kubernetes-namespace
    backstage.plugin-techdocs:
      routeBindings:
        targets:
          - importName: techdocsPlugin
        bindings:
          - bindTarget: catalogPlugin.externalRoutes
            bindMap:
              viewTechDoc: techdocsPlugin.routes.docRoot
          - bindTarget: scaffolderPlugin.externalRoutes
            bindMap:
              viewTechDoc: techdocsPlugin.routes.docRoot
      dynamicRoutes:
        - path: /docs
          importName: TechDocsIndexPage
          menuItem:
            icon: docs
            text: Docs
        - path: /docs/:namespace/:kind/:name/*
          importName: TechDocsReaderPage
      mountPoints:
        - mountPoint: entity.page.docs/cards
          importName: EntityTechdocsContent
          config:
            layout:
              gridColumn: "1 / -1"
            if:
              allOf:
                - isTechDocsAvailable
        - mountPoint: search.page.results
          importName: TechDocsSearchResultListItem
        - mountPoint: search.page.filters
          importName: TechdocsSearchFilter
        - mountPoint: search.page.types
          importName: techdocsSearchType
          config:
            props:
              name: Documentation
              icon: docs
    backstage.plugin-techdocs-module-addons-contrib:
      techdocsAddons:
        - importName: ReportIssue
    backstage-community.plugin-tech-radar:
      apiFactories:
        - importName: TechRadarApi
      appIcons:
        - name: techRadar
          importName: TechRadarIcon
      dynamicRoutes:
        - path: /tech-radar
          importName: TechRadarPage
          menuItem:
            icon: techRadar
            text: Tech Radar
          config:
            props:
              width: 1500
              height: 800
    backstage-community.plugin-analytics-provider-segment:
      analyticsApiExtensions:
        - importName: SegmentAnalytics
    backstage-community.plugin-rbac:
      appIcons:
        - name: rbacIcon
          importName: RbacIcon
      dynamicRoutes:
        - path: /rbac
          importName: RbacPage
          menuItem:
            icon: rbacIcon
            text: RBAC
      menuItems:
        rbac:
          parent: admin
          icon: rbacIcon
    red-hat-developer-hub.backstage-plugin-marketplace:
      appIcons:
        - name: marketplace
          importName: MarketplaceIcon
      dynamicRoutes:
        - path: /extensions/catalog
          importName: DynamicMarketplacePluginRouter
      mountPoints:
        - mountPoint: internal.plugins/tab
          importName: DynamicMarketplacePluginContent
          config:
            path: marketplace
            title: Catalog
    red-hat-developer-hub.backstage-plugin-adoption-insights:
      appIcons:
        - name: adoptionInsightsIcon
          importName: AdoptionInsightsIcon
      dynamicRoutes:
        - path: /adoption-insights
          importName: AdoptionInsightsPage
          menuItem:
            icon: adoptionInsightsIcon
            text: Adoption Insights
      menuItems:
        adoption-insights:
          parent: admin
          icon: adoptionInsightsIcon
    red-hat-developer-hub.backstage-plugin-analytics-module-adoption-insights:
      analyticsApiExtensions:
        - importName: AdoptionInsightsAnalyticsApi
app:
  title: Red Hat Developer Hub
