global:
  clusterRouterBase: ${CLUSTER_ROUTER_BASE}
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      # === Notifications Plugin (Required for Orchestrator) ===
      - package: ./dynamic-plugins/dist/backstage-plugin-notifications-backend-dynamic
        disabled: false

      - package: ./dynamic-plugins/dist/backstage-plugin-notifications
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-notifications:
                dynamicRoutes:
                  - importName: NotificationsPage
                    menuItem:
                      config:
                        props:
                          titleCounterEnabled: true
                          webNotificationsEnabled: false
                      importName: NotificationsSidebarItem
                    path: /notifications

      # === Signals Plugin (Recommended) ===
      - package: ./dynamic-plugins/dist/backstage-plugin-signals-backend-dynamic
        disabled: false

      - package: ./dynamic-plugins/dist/backstage-plugin-signals
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-signals: {}

      # === Orchestrator Plugin Overrides (MUST be last to override dynamic-plugins.default.yaml) ===
      - package: "@redhat/backstage-plugin-orchestrator@1.7.1"
        disabled: false
        integrity: sha512-Cqu9EQwVQ4mpdgWTUA0MW89Gul0IklhvkkqVoO3CloQ1dnAj1XyXikCphzH5TmNDDd9K66dOpaKKCaW9KeJ4WA==
        overrideConfig: true

      - package: "@redhat/backstage-plugin-orchestrator-backend-dynamic@1.7.1"
        disabled: false
        integrity: sha512-9cXbedr0lC7ns7SNqARrWSQI4JGcZFw5xpfpUzA1tJaMMUjzAdPHTXqljf62/fs4hYBK8TJsWJ2KJkGVMzbrHQ==
        overrideConfig: true
        pluginConfig:
          orchestrator:
            dataIndexService:
              url: ${DATA_INDEX_URL}

      - package: "@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@1.7.1"
        disabled: false
        integrity: sha512-J1sTjA5kj6DphG8D65go9KlpIfKyLN/wq+XlY5Cb5djEo8mvF3wn3Haf60OGFo5cP4OfRSWqFwT7LM5/dNVwAg==
        overrideConfig: true
        pluginConfig:
          orchestrator:
            dataIndexService:
              url: ${DATA_INDEX_URL}

      - package: "@redhat/backstage-plugin-orchestrator-form-widgets@1.7.1"
        disabled: false
        integrity: sha512-0KIXrZoJ+O4xNNzN/zB4+VMuaRPuiUviAmM+fIhTo/P9aLA36F9aIlyMbUbki49uaJ0zd8KXMBvmJSHZNrYkGQ==
        overrideConfig: true

# Backstage upstream configuration
upstream:
  backstage:
    appConfig:
      # Guest authentication (required for easy access)
      auth:
        providers:
          guest:
            dangerouslyAllowOutsideDevelopment: true

      # Orchestrator backend configuration
      orchestrator:
        catalog:
          environment: production
        dataIndexService:
          url: ${DATA_INDEX_URL}
          graphql:
            endpoint: /graphql
        editor:
          path: "https://sandbox.kie.org/swf-chrome-extension/0.32.0"

      # Notifications configuration for Orchestrator
      notifications:
        processors:
          orchestratorWorkflowEventsProcessor:
            enabled: true

      # Catalog locations for Orchestrator templates
      catalog:
        locations:
          - type: url
            target: https://github.com/parodos-dev/workflow-software-templates/blob/main/scaffolder-templates/orchestrator-workflows/template.yaml
            rules:
              - allow: [Template]
          - type: url
            target: https://github.com/parodos-dev/serverless-workflows-config/blob/main/catalog-entities/all.yaml
            rules:
              - allow: [Component]
