---
- name: Create service account secret for cost metrics
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    cat << EOF | oc apply -f -
    {{ lookup('template', 'costmanagement_secret.yaml.j2') }}
    EOF
