---
- name: Ensure costmetrics namespace exists
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    cat << EOF | oc apply -f -
    apiVersion: v1
    kind: Namespace
    metadata:
      name: "{{ costmetrics_namespace }}"
    EOF

- name: Install Cost Metrics Operator via OperatorHub
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    cat << EOF | oc apply -f -
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: "{{ costmetrics_operator_name }}"
      namespace: "{{ costmetrics_namespace }}"
    spec:
      channel: "{{ costmetrics_operator_channel }}"
      name: "{{ costmetrics_operator_name }}"
      source: "{{ costmetrics_operator_source }}"
      sourceNamespace: "{{ costmetrics_operator_source_namespace }}"
    EOF
