---
- name: Label namespaces for cost management
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    cat << EOF | oc apply -f -
    apiVersion: v1
    kind: Namespace
    metadata:
      name: "{{ item }}"
      labels:
        insights_cost_management_optimizations: "true"
    EOF
  loop: "{{ costmetrics_label_namespaces }}" 