- name: Enable ceph tools
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc patch storagecluster ocs-storagecluster -n openshift-storage --type json --patch '[{ "op": "replace", "path": "/spec/enableCephTools", "value": true }]'
    oc patch OCSInitialization ocsinit -n openshift-storage --type json --patch  '[{ "op": "replace", "path": "/spec/enableCephTools", "value": true }]'

- name: Capture ceph tools pod
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc get pods -n openshift-storage -l app=rook-ceph-tools --no-headers=true | awk '/Running/ {print $1}'
  register: ceph_tools_pod
  retries: 8
  delay: 10
  until: ceph_tools_pod.stdout != ''

- name: Capture ceph tools pod
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc exec -it -n openshift-storage {{ ceph_tools_pod.stdout_lines[0] }} -- ceph status -f json |\
     jq '.health.status' -r
  register: ceph_status
  failed_when: ceph_status.stdout == ''
  retries: 5
  delay: 2
  until: ceph_status.stdout != ''
