- name: Disable ceph tools
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}" 
  ansible.builtin.shell: |
    oc patch storagecluster ocs-storagecluster -n openshift-storage --type json --patch '[{ "op": "replace", "path": "/spec/enableCephTools", "value": false }]'
    oc patch OCSInitialization ocsinit -n openshift-storage --type json --patch  '[{ "op": "replace", "path": "/spec/enableCephTools", "value": false }]'

- name: Wait for ceph tools pod to be stopped
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}" 
  ansible.builtin.shell: |
    oc get pods -n openshift-storage | grep rook-ceph-tools
  register: ceph_tools_pod
  retries: 8
  delay: 15
  until: ceph_tools_pod.rc == 1
  failed_when: ceph_tools_pod.rc != 1