- name: Apply node recovery
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}" 
  ansible.builtin.shell: |
    cat <<EOF | oc apply -f -
    apiVersion: odf.openshift.io/v1alpha1
    kind: NodeRecovery
    metadata:
      labels:
        app.kubernetes.io/created-by: odf-node-recovery-operator
        app.kubernetes.io/instance: noderecovery-test
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: noderecovery
        app.kubernetes.io/part-of: odf-node-recovery-operator
      name: noderecovery-test
    EOF

- name: Wait for node recovery to complete
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}" 
  ansible.builtin.shell: |
    oc get noderecoveries.odf.openshift.io noderecovery-test -o json | jq '.status.phase' -r
  register: node_recovery
  retries: 30
  delay: 30
  until: node_recovery.stdout == 'Completed'
