- name: Enable ceph tools
  ansible.builtin.import_tasks: enable-ceph-tools.yml

- name: Recreate node
  ansible.builtin.import_tasks: recreate-node.yml

- name: Perform node recovery
  ansible.builtin.import_tasks: node-recovery.yml

- name: Wait until ceph status is healthy
  ansible.builtin.import_tasks: ceph-status.yml
  retries: 8
  delay: 15
  until: "'HEALTH_OK' in {{ ceph_status.stdout }}"

- name: Delete node recovery if it exists
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc delete noderecoveries.odf.openshift.io noderecovery-test
