---
- name: Create optimizer app-config configmap
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.template:
    src: app-config-cm.yaml.j2
    dest: /tmp/app-config-cm.yaml
    mode: "0644"
  register: template_result

- name: Apply the rendered configmap
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc apply -f /tmp/app-config-cm.yaml
  when: template_result.changed
