---
- name: Deploy optimizer app deployment
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.template:
    src: optimizer-deployment.yaml.j2
    dest: /tmp/optimizer-deployment.yaml
    mode: '0644'
  register: deployment_template_result

- name: Apply the rendered deployment
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc apply -f /tmp/optimizer-deployment.yaml
  when: deployment_template_result.changed 