---
- name: Create role for configmap-reader
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc create role configmap-reader \
      --verb=get \
      --resource=configmaps \
      -n "{{ optimizer_namespace }}" \
      --dry-run=client -o yaml | oc apply -f -

- name: Create rolebinding for configmap-reader
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc create rolebinding configmap-reader-binding \
      --role=configmap-reader \
      --serviceaccount="{{ optimizer_namespace }}:default" \
      -n "{{ optimizer_namespace }}" \
      --dry-run=client -o yaml | oc apply -f -
