---
- name: Find the namespace where SonataFlow services are deployed
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ansible.builtin.shell: |
    oc get deployment --all-namespaces | grep sonataflow-platform-data-index-service | awk '{print $1}'
  register: sonataflow_deployment_namespace
  changed_when: false
  failed_when: sonataflow_deployment_namespace.stdout == ""

- name: Display found SonataFlow namespace
  ansible.builtin.debug:
    msg: "Found SonataFlow services in namespace: {{ sonataflow_deployment_namespace.stdout }}"

- name: Set fact for SonataFlow namespace
  ansible.builtin.set_fact:
    sonataflow_namespace: "{{ sonataflow_deployment_namespace.stdout }}"
