---
- name: Discover required namespaces
  import_tasks: discover_namespaces.yml

- name: Create optimizer namespace
  import_tasks: create_namespace.yml

- name: Create optimizer app-config configmap
  import_tasks: create_app_config_cm.yml

- name: Create log4j configmap
  import_tasks: create_log4j_cm.yml

- name: Create role and rolebinding for configmap access
  import_tasks: create_rbac.yml

- name: Label optimizer and sonataflow namespaces
  import_tasks: label_namespaces.yml

- name: Create network policy for optimizer to sonataflow-infra
  import_tasks: create_network_policy.yml

- name: Deploy optimizer app deployment
  import_tasks: create_optimizer_deployment.yml
