apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-jenkins
  namespace: rhdh
  title: "@backstage-community/plugin-jenkins"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-jenkins
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-jenkins
  tags: []
spec:
  packageName: "@backstage-community/plugin-jenkins"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-jenkins
  version: 0.12.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.35.1
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - jenkins
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-jenkins:
              mountPoints:
                - mountPoint: entity.page.ci/cards
                  importName: EntityJenkinsContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isJenkinsAvailable
