# yaml-language-server: $schema=https://raw.githubusercontent.com/redhat-developer/rhdh-plugins/refs/heads/main/workspaces/marketplace/json-schema/packages.json
apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-todo-backend
  namespace: rhdh
  title: "@backstage-community/plugin-todo-backend"
  links:
    - url: https://github.com/backstage/community-plugins/blob/main/workspaces/todo/plugins/todo-backend/README.md
      title: Plugin Overview (README)
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/todo/plugins/todo-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/todo
  tags: []
spec:
  packageName: "@backstage-community/plugin-todo-backend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-todo-backend:bs_1.42.5__0.13.0!backstage-community-plugin-todo-backend
  version: 0.13.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.42.5
  author: Backstage Community
  support: community
  lifecycle: active
  partOf:
    - todo
