apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-catalog-backend-module-gitlab-org
  namespace: rhdh
  title: "@backstage/plugin-catalog-backend-module-gitlab-org"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-gitlab-org-dynamic
  tags:
    - software-catalog
spec:
  packageName: "@backstage/plugin-catalog-backend-module-gitlab-org"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-org-dynamic
  version: 0.2.9
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.39.1
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - gitlab-org-catalog-integration
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            gitlab: {}
