# yaml-language-server: $schema=https://raw.githubusercontent.com/redhat-developer/rhdh-plugins/refs/heads/main/workspaces/marketplace/json-schema/packages.json
apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: dynatrace-backstage-plugin-dql
  namespace: dynatrace
  title: "@dynatrace/backstage-plugin-dql"
  links:
    - url: https://www.dynatrace.com/
      title: Homepage
    - url: https://github.com/Dynatrace/backstage-plugin/issues
      title: Issues
    - title: Source Code
      url: https://github.com/Dynatrace/backstage-plugin
  annotations:
    backstage.io/source-location: url
      https://github.com/Dynatrace/backstage-plugin
  tags: []
spec:
  packageName: "@dynatrace/backstage-plugin-dql"
  #dynamicArtifact: ./dynamic-plugins/dist/dynatrace-backstage-plugin-dql
  version: 2.1.5
  backstage:
    role: frontend-plugin
    supportedVersions: 1.35.1
  author: Dynatrace
  support: production
  lifecycle: active
  partOf:
    - dynatrace-commercial
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            dynatrace.backstage-plugin-dql:
              mountPoints:
                - mountPoint: entity.page.monitoring/cards
                  importName: DynatraceTab
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isDynatraceAvailable
