apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: dynatrace-backstage-plugin-dql-backend
  namespace: dynatrace
  title: "DQL Backend"
  links:
    - url: https://www.dynatrace.com/
      title: Homepage
    - url: https://github.com/Dynatrace/backstage-plugin/issues
      title: Issues
    - title: Source Code
      url: https://github.com/Dynatrace/backstage-plugin
  annotations:
    backstage.io/source-location: url
      https://github.com/Dynatrace/backstage-plugin
  tags: []
spec:
  packageName: "@dynatrace/backstage-plugin-dql-backend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/dynatrace-backstage-plugin-dql-backend:bs_1.42.5__2.3.0!dynatrace-backstage-plugin-dql-backend
  version: 2.3.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.42.5
  author: Dynatrace
  support: production
  lifecycle: active
  partOf:
    - dynatrace-commercial
  appConfigExamples:
    - title: Default configuration
      content:
        dynatrace:
          environments:
            - name: ${DYNATRACE_NAME}
              url: ${DYNATRACE_URL}
              tokenUrl: ${DYNATRACE_TOKEN_URL}
              accountUrn: ${DYNATRACE_ACCOUNT_URN}
              clientId: ${DYNATRACE_CLIENT_ID}
              clientSecret: ${DYNATRACE_CLIENT_SECRET}
