apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-backstage-plugin-argo-cd
  namespace: rhdh
  title: "@roadiehq/backstage-plugin-argo-cd"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/roadiehq-backstage-plugin-argo-cd
  tags: []
spec:
  packageName: "@roadiehq/backstage-plugin-argo-cd"
  dynamicArtifact: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
  version: 2.8.4
  backstage:
    role: frontend-plugin
    supportedVersions: 1.35.1
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - roadiehq-argo-cd
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            roadiehq.backstage-plugin-argo-cd:
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: EntityArgoCDOverviewCard
                  config:
                    layout:
                      gridColumnEnd:
                        lg: span 8
                        xs: span 12
                    if:
                      allOf:
                        - isArgocdAvailable
                - mountPoint: entity.page.cd/cards
                  importName: EntityArgoCDHistoryCard
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isArgocdAvailable
