app:
  title: Red Hat Developer Hub
  baseUrl: ${RHDH_RUNTIME_URL}
backend:
  auth:
    externalAccess:
    - type: legacy
      options:
        subject: legacy-default-config
        secret: "secret"
  baseUrl: ${RHDH_RUNTIME_URL}
  cors:
    origin: ${RHDH_RUNTIME_URL}
  database:
    connection:  # configure Backstage DB connection parameters
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true