apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-plugin-mirror-conf
data:
  rhdh-registries.conf: |
    [[registry]]
    prefix = "registry.access.redhat.com/rhdh"
    location = "${MIRROR_REGISTRY_URL}/rhdh"

    [[registry]]
    prefix = "quay.io/rhdh"
    location = "${MIRROR_REGISTRY_URL}/rhdh"

    [[registry]]
    prefix = "ghcr.io/redhat-developer/rhdh-plugin-export-overlays"
    location = "${MIRROR_REGISTRY_URL}/rhdh-plugin-export-overlays"
