#!/usr/bin/env bash
# Auto-generated by disconnected::ensure_local_amd64_skopeo_shim -- do not edit.
# Rendered from resources/disconnected/skopeo-amd64-shim.sh.tpl via envsubst.
# On aarch64/arm64 hosts, forces --override-os linux --override-arch amd64 for
# skopeo subcommands that operate on OCP/RHDH images (which are linux/amd64).
set -euo pipefail
real_skopeo=${REAL_SKOPEO}
if [[ $# -lt 1 ]]; then
  exec "${real_skopeo}"
fi
cmd=$1
shift
case "${cmd}" in
  copy | inspect | sync | delete | list-tags | tags | mount)
    exec "${real_skopeo}" "${cmd}" --override-os linux --override-arch amd64 "$@"
    ;;
  *)
    exec "${real_skopeo}" "${cmd}" "$@"
    ;;
esac
