apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: showcase
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7007
      targetPort: 7007
      protocol: TCP
  selector:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: backend 