/**
 * Shared pieces of the cluster-free harness Playwright configs
 * (playwright.legacy-local.config.ts and playwright.plugin-sanity.config.ts).
 */

import { resolve } from "path";

import type { PlaywrightTestConfig, ReporterDescription } from "@playwright/test";

export const backendUrl = "http://localhost:7007";
const backendReadiness = `${backendUrl}/.backstage/health/v1/readiness`;
export const isCI = process.env.CI !== undefined && process.env.CI !== "";

// backstage-cli / janus-cli live in the repo-root node_modules/.bin, which
// yarn does not surface for this workspace, so the CLIs are invoked with the
// root .bin prepended to PATH and run from their package directory.
const repoRootBin = resolve(process.cwd(), "..", "node_modules", ".bin");
export const pathWithRepoBin = `${repoRootBin}:${process.env.PATH ?? ""}`;

// Populated by the local-harness populate scripts at the repo root; Playwright
// runs with cwd e2e-tests.
export const dynamicPluginsRoot = resolve(process.cwd(), "..", "dynamic-plugins-root");

/** `list` + `html` + `junit`, with the per-harness suffix applied to the outputs. */
export const harnessReporters = (suffix: string): ReporterDescription[] => [
  ["list"],
  ["html", { open: "never", outputFolder: `playwright-report-${suffix}` }],
  ["junit", { outputFile: process.env.JUNIT_RESULTS ?? `junit-results-${suffix}.xml` }],
];

/**
 * The dynamic-plugins-root entry is generated by the populate scripts and
 * carries the pluginConfig blocks merged by install-dynamic-plugins, so it must
 * come after the static app-config.dynamic-plugins.yaml to win. `extraConfigs`
 * lands last and wins over everything.
 */
export const harnessConfigArgs = (extraConfigs: string[] = []): string =>
  [
    "--config ../../app-config.yaml",
    "--config ../../app-config.dynamic-plugins.yaml",
    "--config ../../app-config.local-e2e.yaml",
    "--config ../../dynamic-plugins-root/app-config.dynamic-plugins.yaml",
    ...extraConfigs.map((config) => `--config ${config}`),
  ].join(" ");

// Playwright declares TestConfigWebServer but does not export it, so the item
// type is recovered from the config surface instead of imported.
type WebServer = Extract<NonNullable<PlaywrightTestConfig["webServer"]>, unknown[]>[number];

/** Mirrors packages/backend's `start` script (--require instrumentation) — keep in sync. */
export const backendWebServer = (extraConfigs: string[] = []): WebServer => ({
  command: `backstage-cli package start --require ./src/instrumentation.js ${harnessConfigArgs(extraConfigs)}`,
  cwd: "../packages/backend",
  env: {
    ...process.env,
    PATH: pathWithRepoBin,
    NODE_OPTIONS: "--no-node-snapshot",
  },
  url: backendReadiness,
  reuseExistingServer: !isCI,
  timeout: 180 * 1000,
  stdout: "pipe",
  stderr: "pipe",
});
