/**
 * Plugin Loader Utilities
 *
 * Utilities for loading and validating dynamic plugins from the catalog index.
 * Used by plugin-dynamic-loading.spec.ts for comprehensive plugin sanity checks.
 */

import { readFileSync, existsSync } from "fs";
import { join } from "path";
import type { JsonObject } from "@backstage/types";
import type { BackendFeature } from "@backstage/backend-plugin-api";

export type PluginRole = "backend" | "frontend";

export type PluginEntry = {
  name: string;
  version: string;
  dirName: string;
  path: string;
  role: PluginRole;
};

export type PluginManifest = {
  backend: PluginEntry[];
  frontend: PluginEntry[];
};

export type LoadedPlugin = {
  plugin: PluginEntry;
  feature: any;
};

export type PluginError = {
  plugin: PluginEntry;
  error: string;
};

/**
 * Load manifest.json generated by install-dynamic-plugins
 */
export function loadManifest(extractDir: string): PluginManifest {
  const manifestPath = join(extractDir, "manifest.json");

  if (!existsSync(manifestPath)) {
    throw new Error(
      `Plugin manifest not found at ${manifestPath}.\n` +
        `Ensure install-dynamic-plugins has been run with CATALOG_INDEX_IMAGE set.`
    );
  }

  return JSON.parse(readFileSync(manifestPath, "utf8"));
}

/**
 * Resolve the entry point for a backend plugin
 */
export function resolveEntryPoint(pluginPath: string): string {
  const pkgPath = join(pluginPath, "package.json");

  if (!existsSync(pkgPath)) {
    throw new Error(`package.json not found in ${pluginPath}`);
  }

  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

  // Try common entry point locations
  const candidates = [
    "dist/index.cjs.js",
    "dist/index.esm.js",
    "dist/index.js",
    pkg.main?.startsWith("dist/") ? pkg.main : undefined,
  ].filter(Boolean) as string[];

  for (const candidate of candidates) {
    const fullPath = join(pluginPath, candidate);
    if (existsSync(fullPath)) {
      return fullPath;
    }
  }

  throw new Error(
    `No entry point found in ${pluginPath}. Tried: ${candidates.join(", ")}`
  );
}

/**
 * Load backend plugins and return loaded plugins and errors
 */
export function loadBackendPlugins(
  plugins: PluginEntry[]
): { loaded: LoadedPlugin[]; errors: PluginError[] } {
  const loaded: LoadedPlugin[] = [];
  const errors: PluginError[] = [];

  for (const plugin of plugins) {
    try {
      const entryPoint = resolveEntryPoint(plugin.path);
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const mod = require(entryPoint) as { default?: BackendFeature };

      if (!mod.default) {
        errors.push({ plugin, error: "No default export" });
        continue;
      }

      loaded.push({ plugin, feature: mod.default });
    } catch (err) {
      errors.push({
        plugin,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return { loaded, errors };
}

/**
 * Validate that a frontend plugin has required bundle artifacts
 */
export function validateFrontendBundle(plugin: PluginEntry): string | null {
  const has = (rel: string) => existsSync(join(plugin.path, rel));

  if (!has("package.json")) {
    return "missing package.json";
  }

  // Frontend plugins should have either dist-scalprum or dist/remoteEntry.js
  if (!has("dist-scalprum") && !has("dist/remoteEntry.js")) {
    return "missing dist-scalprum/ and dist/remoteEntry.js";
  }

  // If dist-scalprum exists, it should have plugin-manifest.json
  if (has("dist-scalprum") && !has("dist-scalprum/plugin-manifest.json")) {
    return "missing dist-scalprum/plugin-manifest.json";
  }

  return null;
}

/**
 * Minimal config overrides for plugins that validate config at startup
 */
const CONFIG_OVERRIDES: Record<string, JsonObject> = {
  "backstage-community-plugin-jenkins-backend": {
    jenkins: {
      baseUrl: "http://localhost:8080",
      username: "test",
      apiKey: "test",
    },
  },
  "backstage-community-plugin-quay-backend": {
    quay: {
      uiUrl: "https://quay.io",
      apiUrl: "https://quay.io/api/v1",
    },
  },
  "immobiliarelabs-backstage-plugin-gitlab-backend": {
    integrations: {
      gitlab: [{ host: "gitlab.com", token: "test" }],
    },
  },
};

/**
 * Build merged config for plugins that require specific config at startup
 */
export function buildMergedConfig(plugins: LoadedPlugin[]): JsonObject {
  const merged: Record<string, any> = {};

  for (const { plugin } of plugins) {
    const overrides = CONFIG_OVERRIDES[plugin.dirName];
    if (overrides) {
      Object.assign(merged, overrides);
    }
  }

  return merged as JsonObject;
}

/**
 * Known plugin failures due to environmental constraints
 *
 * These plugins are skipped during testing because they cannot load in the test environment.
 * Each entry includes the reason for exclusion to help determine if it can be re-enabled later.
 */
export const KNOWN_FAILURES = new Set<string>([
  // Module resolution issue with @pagerduty/backstage-plugin-backend/package.json
  "pagerduty-backstage-plugin-backend",

  // Conflicts with backstage-community argocd (both register pluginId 'argocd')
  "roadiehq-backstage-plugin-argo-cd-backend",

  // Orchestrator plugins require @backstage-community/plugin-rbac-common peer dep
  "red-hat-developer-hub-backstage-plugin-orchestrator-backend",
  "red-hat-developer-hub-backstage-plugin-orchestrator-backend-module-loki",
  "red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator",
]);
