/**
 * Plugin Loader Utilities
 *
 * Core logic for loading and validating dynamic plugins from the catalog index.
 * Used by plugin-dynamic-loading.spec.ts for comprehensive plugin sanity checks.
 */

import { readFileSync, existsSync } from "fs";
import { join } from "path";
import type { BackendFeature } from "@backstage/backend-plugin-api";
import type {
  PluginEntry,
  PluginManifest,
  LoadedPlugin,
  PluginError,
} from "./plugin-types";

/**
 * Load manifest.json generated by install-dynamic-plugins
 */
export function loadManifest(extractDir: string): PluginManifest {
  const manifestPath = join(extractDir, "manifest.json");

  if (!existsSync(manifestPath)) {
    throw new Error(
      `Plugin manifest not found at ${manifestPath}.\n` +
        `Ensure install-dynamic-plugins has been run with CATALOG_INDEX_IMAGE set.`,
    );
  }

  return JSON.parse(readFileSync(manifestPath, "utf8"));
}

/**
 * Resolve the entry point for a backend plugin
 */
export function resolveEntryPoint(pluginPath: string): string {
  const pkgPath = join(pluginPath, "package.json");

  if (!existsSync(pkgPath)) {
    throw new Error(`package.json not found in ${pluginPath}`);
  }

  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

  // Try common entry point locations
  const candidates = [
    "dist/index.cjs.js",
    "dist/index.esm.js",
    "dist/index.js",
    pkg.main?.startsWith("dist/") ? pkg.main : undefined,
  ].filter(Boolean) as string[];

  for (const candidate of candidates) {
    const fullPath = join(pluginPath, candidate);
    if (existsSync(fullPath)) {
      return fullPath;
    }
  }

  throw new Error(
    `No entry point found in ${pluginPath}.\n` +
      `Tried: ${candidates.join(", ")}\n` +
      `package.json main: ${pkg.main || "(not set)"}`,
  );
}

/**
 * Load backend plugins and return loaded plugins and errors
 */
export function loadBackendPlugins(plugins: PluginEntry[]): {
  loaded: LoadedPlugin[];
  errors: PluginError[];
} {
  const loaded: LoadedPlugin[] = [];
  const errors: PluginError[] = [];

  for (const plugin of plugins) {
    try {
      const entryPoint = resolveEntryPoint(plugin.path);
      // eslint-disable-next-line @typescript-eslint/no-require-imports -- Dynamic loading of OCI plugins requires CommonJS require
      const mod = require(entryPoint) as { default?: BackendFeature };

      if (!mod.default) {
        errors.push({ plugin, error: "No default export" });
        continue;
      }

      loaded.push({ plugin, feature: mod.default });
    } catch (err) {
      errors.push({
        plugin,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return { loaded, errors };
}

/**
 * Validate that a frontend plugin has required bundle artifacts
 *
 * Frontend plugins use either:
 * - Modern: dist-scalprum/ with plugin-manifest.json
 * - Legacy: dist/remoteEntry.js (no manifest needed)
 */
export function validateFrontendBundle(plugin: PluginEntry): string | null {
  const has = (rel: string) => existsSync(join(plugin.path, rel));

  if (!has("package.json")) {
    return "missing package.json";
  }

  // Must have at least one bundle format
  if (!has("dist-scalprum") && !has("dist/remoteEntry.js")) {
    return "missing both dist-scalprum/ and dist/remoteEntry.js - needs at least one";
  }

  // Modern dist-scalprum format requires plugin-manifest.json
  if (has("dist-scalprum") && !has("dist-scalprum/plugin-manifest.json")) {
    return "dist-scalprum/ found but missing plugin-manifest.json";
  }

  return null;
}
