kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha2
metadata: 
  name: rhdh
spec:
  application:
    image: 'quay.io/rhdh-community/rhdh:next'
    appConfig:
      configMaps:
        - name: app-config-rhdh
        - name: dynamic-plugins-config
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      envs:
        - name: NODE_OPTIONS
          value: '--no-node-snapshot'
      secrets:
        - name: rhdh-secrets
        - name: redis-secret
