kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha5
metadata:
  name: rhdh
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
        - name: dynamic-plugins-config
        - name: dynamic-global-floating-action-button-config
        - name: dynamic-global-header-config
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      envs:
        - name: NODE_OPTIONS
          value: "--no-node-snapshot"
        - name: NODE_ENV
          value: "production"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: rhdh-secrets
        - name: redis-secret

  # v1alpha5 does not support `spec.application.image`.
  # Override the generated Deployment instead.
  deployment:
    patch:
      spec:
        template:
          spec:
            initContainers:
              - name: install-dynamic-plugins
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
            containers:
              - name: backstage-backend
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
