kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha2
metadata:
  name: rhdh
spec:
  application:
    image: "quay.io/rhdh/rhdh-rhel9-operator:1-8.53"
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
      secrets:
        - name: postgres-crt
          key: postgres-crt.pem
    extraEnvs:
      secrets:
        - name: postgres-cred
    route:
      enabled: true
  database:
    enableLocalDb: false
