#!/bin/bash
#
# Populates dynamic-plugins-root with EVERY OCI plugin from the catalog index,
# for the cluster-free plugin sanity check (playwright.plugin-sanity.config.ts).
#
# The index ships most plugins disabled by default (products opt in via their
# own config), so a plain `includes` config would install nothing. This script
# lists the index's declared packages (shared parser: catalog-index-refs.sh),
# generates an install config that re-enables every one of them, and delegates
# the install to populate.sh. Local `./dynamic-plugins/dist` entries only exist
# inside the product image and are skipped by the CLI as usual.
#
# Requires skopeo and jq. Usage:
#   CATALOG_INDEX_IMAGE=quay.io/rhdh/plugin-catalog-index:next \
#     ./e2e-tests/local-harness/populate-catalog-index.sh
set -e

: "${CATALOG_INDEX_IMAGE:?CATALOG_INDEX_IMAGE must be set (e.g. quay.io/rhdh/plugin-catalog-index:next)}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

refs="$("$DIR/catalog-index-refs.sh" "$CATALOG_INDEX_IMAGE")"

if [[ -z "$refs" ]]; then
  echo "No packages found in dynamic-plugins.default.yaml of ${CATALOG_INDEX_IMAGE}" >&2
  exit 1
fi

{
  echo "# Generated by populate-catalog-index.sh for ${CATALOG_INDEX_IMAGE}"
  echo "includes:"
  echo "  - dynamic-plugins.default.yaml"
  echo "plugins:"
  while read -r ref; do
    echo "  - package: \"$ref\""
    echo "    disabled: false"
  done <<< "$refs"
} > "$workdir/dynamic-plugins.catalog-index.yaml"

echo "Enabling $(echo "$refs" | wc -l | tr -d ' ') package(s) from ${CATALOG_INDEX_IMAGE}"

"$DIR/populate.sh" "$workdir/dynamic-plugins.catalog-index.yaml"

# Record what this run was SUPPOSED to install, so the sanity spec can assert
# it actually got the full index set. Without this the spec only checks
# "installed ⊆ loaded", which passes green even when a registry hiccup, an
# over-broad exclude pattern or a stale populate left it with a handful of
# plugins - the exact silent-underrun this check exists to catch.
# Only oci:// refs are counted: ./dynamic-plugins/dist entries live inside the
# product image and the install CLI skips them outside it.
REPO_ROOT="$(cd "$DIR/../.." && pwd)"
{
  echo "# Generated by populate-catalog-index.sh - do not edit."
  echo "image=${CATALOG_INDEX_IMAGE}"
  echo "$refs" | grep -c '^oci://' | sed 's/^/expected_oci_packages=/'
} > "$REPO_ROOT/dynamic-plugins-root/.catalog-index-refs"
