kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
  labels:
    backstage.io/kubernetes-id: developer-hub
data:
  rbac-policy.csv: |
    p, role:default/admin, catalog-entity, read, allow
    p, role:default/admin, catalog.entity.create, create, allow
    p, role:default/admin, catalog-entity, update, allow
    p, role:default/admin, catalog-entity, delete, allow

    p, role:default/admin, catalog.location.read, read, allow
    p, role:default/admin, catalog.location.create, create, allow
    p, role:default/admin, catalog.location.delete, delete, allow

    p, role:default/admin, scaffolder-action, use, allow
    p, role:default/admin, scaffolder-template, read, allow
    p, role:default/admin, scaffolder.task.read, read, allow

    p, role:default/admin, kubernetes.proxy, use, allow

    p, role:default/admin, catalog.entity.read, read, allow

    p, role:default/admin, policy-entity, read, allow
    p, role:default/admin, policy.entity.create, create, allow

    g, user:development/guest, role:default/admin
  conditional-policies.yaml: |
    result: CONDITIONAL
    roleEntityRef: 'role:default/test2-role'
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
      - update
    conditions:
      rule: IS_ENTITY_OWNER
      resourceType: catalog-entity
      params:
        claims:
          - 'group:janus-qe/rhdh-qe-2-team'
          - \$currentUser
    ---
    result: CONDITIONAL
    roleEntityRef: 'role:default/test2-role'
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - delete
    conditions:
      rule: IS_ENTITY_OWNER
      resourceType: catalog-entity
      params:
        claims:
          - \$currentUser
    ---
    result: CONDITIONAL
    roleEntityRef: 'role:default/transitive-owner'
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      rule: IS_ENTITY_OWNER
      resourceType: catalog-entity
      params:
        claims:
          - \$ownerRefs
    ---
    result: CONDITIONAL
    roleEntityRef: 'role:default/owned_resource_reader'
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      rule: IS_ENTITY_OWNER
      resourceType: catalog-entity
      params:
        claims:
          - \$currentUser
    ---
    result: CONDITIONAL
    roleEntityRef: 'role:default/conditional_denier'
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      rule: HAS_LABEL
      resourceType: catalog-entity
      params:
        label: test-label