# AKS-specific app-config additions
# This file is merged with the base app-config.yaml

# Kubernetes plugin configuration for AKS
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: ${K8S_CLUSTER_URL}
          name: aks-cluster
          authProvider: 'serviceAccount'
          serviceAccountToken: ${K8S_CLUSTER_TOKEN}
          skipTLSVerify: true
          skipMetricsLookup: true

# Azure DevOps integration
integrations:
  azure:
    - host: dev.azure.com
      token: ${AZURE_TOKEN}

# Backend configuration for AKS
backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}

# Azure-specific proxy configurations
proxy:
  '/azure-devops/api':
    target: https://dev.azure.com/
    changeOrigin: true
    headers:
      Authorization: Bearer ${AZURE_TOKEN}

# Monitoring configuration for Azure
monitoring:
  azure:
    enabled: true
    workspace: ${AZURE_LOG_ANALYTICS_WORKSPACE} 