import { mkdtempSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";

import { afterEach, describe, expect, it } from "vitest";

import { readCatalogIndexExpectation } from "../playwright/utils/plugin-loader";

const dirs: string[] = [];

function rootWith(contents: string | null): string {
  const dir = mkdtempSync(join(tmpdir(), "catalog-index-refs-"));
  dirs.push(dir);
  if (contents !== null) {
    writeFileSync(join(dir, ".catalog-index-refs"), contents);
  }
  return dir;
}

afterEach(() => {
  for (const dir of dirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

describe("readCatalogIndexExpectation", () => {
  it("parses the breadcrumb written by populate-catalog-index.sh", () => {
    const root = rootWith(
      "# Generated by populate-catalog-index.sh - do not edit.\n" +
        "image=quay.io/rhdh/plugin-catalog-index:next\n" +
        "expected_oci_packages=13\n",
    );

    expect(readCatalogIndexExpectation(root)).toEqual({
      image: "quay.io/rhdh/plugin-catalog-index:next",
      expectedOciPackages: 13,
    });
  });

  it("keeps digest refs intact (the value contains '=' only in tags, but '@' and ':' must survive)", () => {
    const root = rootWith(
      "image=quay.io/rhdh/plugin-catalog-index@sha256:abc123\nexpected_oci_packages=7\n",
    );

    expect(readCatalogIndexExpectation(root)?.image).toBe(
      "quay.io/rhdh/plugin-catalog-index@sha256:abc123",
    );
  });

  it("returns null when the harness was populated by the curated populate.sh", () => {
    expect(readCatalogIndexExpectation(rootWith(null))).toBeNull();
  });

  it.each([
    ["missing image", "expected_oci_packages=13\n"],
    ["missing count", "image=quay.io/rhdh/plugin-catalog-index:next\n"],
    ["empty count", "image=quay.io/x:next\nexpected_oci_packages=\n"],
    ["non-numeric count", "image=quay.io/x:next\nexpected_oci_packages=lots\n"],
  ])("throws on a malformed breadcrumb (%s)", (_label, contents) => {
    expect(() => readCatalogIndexExpectation(rootWith(contents))).toThrow(/Malformed/u);
  });
});
