import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { dirname, join } from "path";

import { afterEach, describe, expect, it } from "vitest";

import {
  parseLoadedPluginNames,
  readCatalogIndexExpectation,
  scanInstalledPlugins,
  validateFrontendBundle,
  validateFrontendBundles,
  type PluginEntry,
} from "../playwright/utils/plugin-loader";

const dirs: string[] = [];

function tempDir(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  dirs.push(dir);
  return dir;
}

function rootWith(contents: string | null): string {
  const dir = tempDir("catalog-index-refs-");
  if (contents !== null) {
    writeFileSync(join(dir, ".catalog-index-refs"), contents);
  }
  return dir;
}

type PluginFixture = { pkg?: unknown; files?: string[] };

/**
 * Builds an install directory: each key is a plugin directory, `pkg` is written
 * as its package.json (omit for a non-plugin directory), and `files` are touched
 * relative to it.
 */
function installDirWith(plugins: Record<string, PluginFixture>): string {
  const root = tempDir("dynamic-plugins-root-");
  for (const [name, { pkg, files = [] }] of Object.entries(plugins)) {
    const pluginDir = join(root, name);
    mkdirSync(pluginDir, { recursive: true });
    if (pkg !== undefined) {
      writeFileSync(join(pluginDir, "package.json"), JSON.stringify(pkg));
    }
    for (const file of files) {
      const target = join(pluginDir, file);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, "");
    }
  }
  return root;
}

function entryFor(path: string): PluginEntry {
  return { name: "p", version: "1.0.0", dirName: "p", path };
}

afterEach(() => {
  for (const dir of dirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

describe("readCatalogIndexExpectation", () => {
  it("parses the breadcrumb written by populate-catalog-index.sh", () => {
    const root = rootWith(
      "# Generated by populate-catalog-index.sh - do not edit.\n" +
        "image=quay.io/rhdh/plugin-catalog-index:next\n" +
        "expected_oci_packages=13\n",
    );

    expect(readCatalogIndexExpectation(root)).toEqual({
      image: "quay.io/rhdh/plugin-catalog-index:next",
      expectedOciPackages: 13,
    });
  });

  it("keeps digest refs intact ('@' and ':' must survive the key/value split)", () => {
    const root = rootWith(
      "image=quay.io/rhdh/plugin-catalog-index@sha256:abc123\nexpected_oci_packages=7\n",
    );

    expect(readCatalogIndexExpectation(root)?.image).toBe(
      "quay.io/rhdh/plugin-catalog-index@sha256:abc123",
    );
  });

  it("returns null when the harness was populated by the curated populate.sh", () => {
    expect(readCatalogIndexExpectation(rootWith(null))).toBeNull();
  });

  it.each([
    ["missing image", "expected_oci_packages=13\n"],
    ["missing count", "image=quay.io/rhdh/plugin-catalog-index:next\n"],
    ["empty count", "image=quay.io/x:next\nexpected_oci_packages=\n"],
    ["non-numeric count", "image=quay.io/x:next\nexpected_oci_packages=lots\n"],
  ])("throws on a malformed breadcrumb (%s)", (_label, contents) => {
    expect(() => readCatalogIndexExpectation(rootWith(contents))).toThrow(/Malformed/u);
  });
});

describe("scanInstalledPlugins", () => {
  it("classifies by backstage.role", () => {
    const root = installDirWith({
      "be-plugin": { pkg: { name: "be", backstage: { role: "backend-plugin" } } },
      "be-module": { pkg: { name: "be-mod", backstage: { role: "backend-plugin-module" } } },
      "fe-plugin": { pkg: { name: "fe", backstage: { role: "frontend-plugin" } } },
      "fe-module": { pkg: { name: "fe-mod", backstage: { role: "frontend-plugin-module" } } },
    });

    const { backend, frontend } = scanInstalledPlugins(root);

    expect(backend.map((p) => p.name).toSorted()).toEqual(["be", "be-mod"]);
    expect(frontend.map((p) => p.name).toSorted()).toEqual(["fe", "fe-mod"]);
  });

  it("does not treat a library role as a frontend bundle", () => {
    // Only "frontend*" is frontend: a library classified as frontend would be
    // failed by validateFrontendBundle for shipping no bundle.
    const root = installDirWith({
      lib: { pkg: { name: "lib", backstage: { role: "node-library" } } },
    });

    const { backend, frontend } = scanInstalledPlugins(root);

    expect(frontend).toEqual([]);
    expect(backend.map((p) => p.name)).toEqual(["lib"]);
  });

  it.each([
    ["dist-scalprum", ["dist-scalprum/plugin-manifest.json"], "frontend"],
    ["legacy remoteEntry", ["dist/remoteEntry.js"], "frontend"],
    ["no bundle", [], "backend"],
  ])("falls back to bundle layout when the role is absent (%s)", (_label, files, expected) => {
    const root = installDirWith({ p: { pkg: { name: "p" }, files } });

    const { backend, frontend } = scanInstalledPlugins(root);

    expect(frontend.length).toBe(expected === "frontend" ? 1 : 0);
    expect(backend.length).toBe(expected === "backend" ? 1 : 0);
  });

  it("skips directories without a package.json", () => {
    const root = installDirWith({
      "catalog-entities": { files: ["entity.yaml"] },
      plugin: { pkg: { name: "plugin", backstage: { role: "backend-plugin" } } },
    });

    expect(scanInstalledPlugins(root).backend.map((p) => p.name)).toEqual(["plugin"]);
  });

  it("carries name and version from package.json and dirName from disk", () => {
    const root = installDirWith({
      "some-dir": { pkg: { name: "@scope/plugin", version: "2.3.4" } },
    });

    expect(scanInstalledPlugins(root).backend[0]).toMatchObject({
      name: "@scope/plugin",
      version: "2.3.4",
      dirName: "some-dir",
    });
  });

  it("defaults the version when package.json omits it", () => {
    const root = installDirWith({ p: { pkg: { name: "p" } } });

    expect(scanInstalledPlugins(root).backend[0].version).toBe("unknown");
  });

  it("throws when nothing is installed", () => {
    expect(() => scanInstalledPlugins(installDirWith({}))).toThrow(/No installed plugins found/u);
  });

  it("names the file when a package.json is malformed", () => {
    const root = tempDir("dynamic-plugins-root-");
    mkdirSync(join(root, "broken"), { recursive: true });
    writeFileSync(join(root, "broken", "package.json"), "{ truncated");

    expect(() => scanInstalledPlugins(root)).toThrow(/Malformed .*broken.*package\.json/u);
  });
});

describe("validateFrontendBundle", () => {
  it("accepts a dist-scalprum bundle with its manifest", () => {
    const root = installDirWith({
      p: { pkg: { name: "p" }, files: ["dist-scalprum/plugin-manifest.json"] },
    });

    expect(validateFrontendBundle(entryFor(join(root, "p")))).toBeNull();
  });

  it("accepts a legacy remoteEntry bundle", () => {
    const root = installDirWith({ p: { pkg: { name: "p" }, files: ["dist/remoteEntry.js"] } });

    expect(validateFrontendBundle(entryFor(join(root, "p")))).toBeNull();
  });

  it("rejects a plugin shipping neither bundle format", () => {
    const root = installDirWith({ p: { pkg: { name: "p" } } });

    expect(validateFrontendBundle(entryFor(join(root, "p")))).toMatch(/missing both/u);
  });

  it("rejects a dist-scalprum bundle without its manifest", () => {
    const root = installDirWith({ p: { pkg: { name: "p" }, files: ["dist-scalprum/main.js"] } });

    expect(validateFrontendBundle(entryFor(join(root, "p")))).toMatch(/missing plugin-manifest/u);
  });
});

describe("validateFrontendBundles", () => {
  it("returns no errors when every plugin ships a bundle", () => {
    const root = installDirWith({
      a: { pkg: { name: "a" }, files: ["dist/remoteEntry.js"] },
      b: { pkg: { name: "b" }, files: ["dist-scalprum/plugin-manifest.json"] },
    });

    expect(validateFrontendBundles([entryFor(join(root, "a")), entryFor(join(root, "b"))])).toEqual(
      [],
    );
  });

  it("reports one entry per broken plugin and omits the valid ones", () => {
    const root = installDirWith({
      good: { pkg: { name: "good" }, files: ["dist/remoteEntry.js"] },
      bad: { pkg: { name: "bad" } },
    });
    const broken = entryFor(join(root, "bad"));

    const errors = validateFrontendBundles([entryFor(join(root, "good")), broken]);

    expect(errors).toHaveLength(1);
    expect(errors[0].plugin).toBe(broken);
    expect(errors[0].error).toMatch(/missing both/u);
  });
});

describe("parseLoadedPluginNames", () => {
  it("collects the package names", () => {
    expect(parseLoadedPluginNames([{ name: "a", version: "1" }, { name: "b" }])).toEqual(
      new Set(["a", "b"]),
    );
  });

  it("dedupes repeated names", () => {
    expect(parseLoadedPluginNames([{ name: "a" }, { name: "a" }]).size).toBe(1);
  });

  it("returns an empty set for an empty response", () => {
    expect(parseLoadedPluginNames([])).toEqual(new Set());
  });

  it.each([[{}], ["a string"], [null], [42]])(
    "throws when the payload is not an array (%s)",
    (body) => {
      expect(() => parseLoadedPluginNames(body)).toThrow(
        /Expected loaded-plugins response to be an array/u,
      );
    },
  );

  it.each([[[{ version: "1" }]], [[{ name: 42 }]], [[null]], [["plugin-a"]]])(
    "throws on an item without a string name (%s)",
    (body) => {
      expect(() => parseLoadedPluginNames(body)).toThrow(/without a string name/u);
    },
  );
});
