- name: Set wf vars
  ansible.builtin.set_fact:
    wf_entry: "{{ wf_entry_var }}"
    wf_version: "{{ wf_version_var }}"

- name: Find latest helm chart version
  vars:
    wf_regex: "{{ '^1.' + milestone|string }}"
  when: wf_version == ''
  block:
    - name: Debug out curl command for troubleshooting
      ansible.builtin.debug:
        msg: |
          curl {{ workflow_helm_index }} | yq .entries.{{ wf_entry }}[].version | egrep "{{ wf_regex }}"" | head -n1

    - name: Get JSON data from API
      ansible.builtin.uri:
        url: "{{ workflow_helm_index }}"
        method: GET
        return_content: yes
      register: wf_tags_raw

    - name: Set fact for latest version
      vars:
        wf_tags_yaml: "{{ (wf_tags_raw.content | from_yaml).entries }}"
      ansible.builtin.set_fact: 
        wf_version: "{{ (wf_tags_yaml[wf_entry] | selectattr('version', 'match', wf_regex) | first).version }}"  

- name: Debug output chosen version
  ansible.builtin.debug:
    msg: |
      {{ wf_entry }} version to install is {{ wf_version }}
