name: E2E Bash

on:
  pull_request:
    branches:
      - 'main'
      - 'release-[0-9]+.[0-9]+'
    paths:
      - '.ci/**'
      - '.shellcheckrc'

jobs:
  lint:
    name: ShellCheck and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        working-directory: ./.ci
        run: yarn install

      - name: Run ShellCheck check
        working-directory: ./.ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn shellcheck

      - name: Run Prettier check
        working-directory: ./.ci
        run: yarn prettier:check
