# Copyright Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: PR

on:
  pull_request:

env:
  TURBO_SCM_BASE: ${{ github.event.pull_request.base.sha }}
  TURBO_SCM_HEAD: ${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr-comments:
    runs-on: ubuntu-latest
    outputs:
      skip-test: ${{ steps.check-skip-test.outputs.skip-test }}
    steps:
      - name: Check PR comments to determine if tests should be skipped
        id: check-skip-test
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number
              });
              const shouldSkip = comments.data.some(comment => comment.body.includes('/skip-e2e'));
              if (shouldSkip) {
                console.log("Skipping E2E tests due to /skip-e2e comment");
              }
              core.setOutput('skip-test', shouldSkip);
            } catch (error) {
              console.error("Error checking comments:", error);
              core.setFailed("Failed to check PR comments");
            }

  build:
    name: Build with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Check Image and Relevant Changes
        id: check-image
        uses: ./.github/actions/check-image-and-changes

      - name: Check if build should be skipped
        run: |
          if [[ "${{ steps.check-image.outputs.relevant_changes }}" == "false" && "${{ steps.check-image.outputs.image_exists }}" == "true" ]]; then
            echo "Skipping build: Image already exists and no relevant changes detected."
            exit 0
          fi

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup local Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@cc723b4600e40a6b8815b65701d8614b91e2669e # v1

      - name: Use app-config.example.yaml
        run: rm app-config.yaml && mv app-config.example.yaml app-config.yaml

      - name: Install dependencies
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Build packages
        run: yarn run build --continue --affected

  test:
    needs: check-pr-comments
    name: Test with Node.js ${{ matrix.node-version }}
    if: "!contains(github.event.pull_request.title, '[skip e2e]') && !needs.check-pr-comments.outputs.skip-test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Check Image and Relevant Changes
        id: check-image
        uses: ./.github/actions/check-image-and-changes

      - name: Check if tests should be skipped
        run: |
          if [[ "${{ steps.check-image.outputs.relevant_changes }}" == "false" && "${{ steps.check-image.outputs.image_exists }}" == "true" ]]; then
            echo "Skipping tests: No relevant changes detected."
            exit 0
          fi

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup local Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@cc723b4600e40a6b8815b65701d8614b91e2669e # v1

      - name: Use app-config.example.yaml
        run: rm app-config.yaml && mv app-config.example.yaml app-config.yaml

      - name: Install dependencies
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Run prettier
        run: yarn prettier:check --continue --affected

      - name: Run lint
        run: yarn run lint:check --continue --affected

      - name: Run monorepo tools
        run: yarn run monorepo:check

      - name: Regenerate dockerfiles
        run: |
          yarn run build:dockerfile; if [[ $(git diff --name-only | grep Dockerfile || true) != "" ]]; then \
            echo "ERROR: Workspace is dirty! Must run 'yarn build:dockerfile' and commit changes!"; exit 1; \
          fi

      - name: Run tests
        run: yarn run test --continue --affected

      - name: Verify wrappers
        run: yarn workspace dynamic-plugins-utils run test:wrappers
