apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: backstage-scc
  annotations:
    kubernetes.io/description: "SecurityContextConstraints for RHDH Backstage application"
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1001
      max: 1001
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1001
  uidRangeMax: 1001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 1001
      max: 1001
users:
  - system:serviceaccount:showcase:rhdh-service-account
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret 