# OpenShift-specific variables

cluster_type: "openshift"

# OpenShift Route configuration (instead of Ingress)
route:
  enabled: true
  tls:
    enabled: true
    termination: "edge"

# Ingress disabled for OpenShift (uses Routes)
ingress:
  enabled: false

# OpenShift-specific resource configurations
resources:
  security_context:
    run_as_non_root: true
    run_as_user: 1001
    fs_group: 1001

# OpenShift image configuration
image:
  registry: "quay.io"
  repository: "rhdh/rhdh-hub-rhel9"

# OpenShift-specific environment variables
environment_vars:
  OPENSHIFT_ENABLED: "true"
  ROUTER_TYPE: "openshift"

# OpenShift-specific plugins
dynamic_plugins:
  - package: "@openshift/backstage-plugin-kubernetes"
    disabled: false
  - package: "@backstage/plugin-techdocs"
    disabled: false
  - package: "@janus-idp/backstage-plugin-rbac"
    disabled: false

# Security Context Constraints
security_context_constraints:
  enabled: true
  name: "backstage-scc"

# OpenShift-specific networking
networking:
  service_mesh_enabled: false
  network_policies_enabled: true

# OpenShift storage classes
storage:
  default_storage_class: "gp2"
  postgresql_storage_class: "gp2"
  redis_storage_class: "gp2"

# OpenShift-specific features
features:
  oauth_proxy_enabled: false
  pipeline_integration: true
  operator_framework: true

# Default OpenShift cluster names
cluster_names:
  default: "openshift-cluster"
  ephemeral_prefix: "ocp-"
